# This workflow uses the common build and push Docker image workflow
name: Use Common Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      branch:
        required: false
        type: string
        default: main
      build_command:
        required: false
        type: string
        default: mvn clean package
      dockerfile_path:
        required: true
        type: string
      docker_tags:
        required: false
        type: string
        default: latest
      push_image:
        required: false
        type: boolean
        default: true    
  push:
    branches:
      - main

jobs:
  build-and-push:
    uses: nookyo/workflow-hub/.github/workflows/common-build-docker-image.yaml@main    
    with:
      branch: main 
      build_command: "mvn clean package"
      dockerfile_path: "Dockerfile"
      docker_tags: "latest"
      push_image: true
